### ISSUE TITLE
Add aocHandleFaultData and wakeUpCommandOffset

### ISSUE THREAD

**Issue by wkoiking** [ohri-anurag/ASPMS#8]
According to following commit:
<https://github.com/wkoiking/VDU/commit/6837657cc25bc23c277ee3fe4d675a3ebbb744aa> and <https://github.com/wkoiking/VDU/commit/0e497e1ca65d1e8d6c8235d2d14fe515ea0e82c5>

Add GUI to edit aocHandleFaultData and wakeUpCommandOffset to ASPMS.

**Comment by ohri-anurag** [comment]
Done via commit e9d9968a482dddd9e61db0936e855405d5b5b23e
